Add dedicated linker section for firmware version string
01org/zephyr pull request #7
Opened 2017-03-16 18:48 UTC by bigdinotech

Using a special macro DEFINE_FIRMWARE_VERSION_STRING(), you can
declare a string in C code which is guaranteed to be at 0x40033FC0

2017-03-16 18:48 UTC, bigdinotech commented
@eriknyquist please review

2017-03-16 19:53 UTC, eriknyquist requested changes

2017-03-16 19:53 UTC, eriknyquist commented on include/arch/x86/linker.ld
> +	. = ALIGN(0x40033FC0);
don't do this!!

You are setting the location counter to the next address on a 0x40033FC0 byte boundary. This is wrong for three reasons

1) This is a hack. There is already a way to declare a fixed load address for a section, just google "Fixed load address for linker section" to get the syntax

2) Due to the size of flash, ALIGN(0x40033FC0) *will* coincidentally set the location counter to exactly 0x40033FC0, but it is entirely dependent on the size of flash (i.e. you might get 0x0, or 0x80067F80 depending on the size of flash)

3) You're setting the location counter to 0x40033FC0. So all "romable" sections after this one will be after 0x40033FC0..... meaning we'll probably lose a bunch of stuff

2017-03-16 19:57 UTC, eriknyquist commented on include/arch/x86/linker.ld
> +	. = ALIGN(0x40033FC0);
Give the address a name, put it in linker-defs with all the other defs.
Surely you're aware by now that this is something we need to do?

Just always assume that you need to do this. We really don't need to spend time on trivial things like this in code review.

2017-03-16 21:20 UTC, eriknyquist commented on include/linker-defs.h
> +#define VERSION_SECTION_SIZE 32
Use this to define the start address. E.g. add a new define for the last address in Flash (or maybe it's already there). then the start address of the VERSION section is "FLASH_END - VERSION_SECTION_SIZE"

2017-03-16 22:39 UTC, bigdinotech commented
@eriknyquist please review

2017-03-16 23:10 UTC, eriknyquist commented on include/arch/x86/linker.ld
> +	_version_rom_start = FIRMWARE_FLASH_END - VERSION_SECTION_SIZE;
put in linker-defs.h, with the others.....

2017-03-16 23:11 UTC, eriknyquist commented on include/arch/x86/linker.ld
> +	_VERSION_SECTION_NAME _version_rom_start :
Looks good. Let's use SECTION_PROLOGUE to match the rest of the file though

    SECTION_PROLOGUE(_VERSION_SECTION_NAME, _version_rom_start (OPTIONAL),)

2017-03-17 16:58 UTC, bigdinotech commented
@eriknyquist please review

2017-03-17 21:18 UTC, bigdinotech commented
@eriknyquist please review again haha

2017-03-17 21:22 UTC, eriknyquist approved these changes

2017-03-20 17:49 UTC, eriknyquist commented
This won't compile for me (?). I made the same change to my own PR #6 (which has more info anyway), closing this one.

2017-03-20 18:24 UTC, eriknyquist commented
replaced by #6

2017-03-20 18:24 UTC, closed without merging